# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "JcIlMmUPF8IXcMOp9b3qm02xizi4moD1rml7eAz2aJdidL+JTaOlfH4pCvPs9HDC1IT+fvxn30t0pNr9HgkPm5BgysxsevhZciu3QU2fj0EjtahmeNVxc7COQtJeAFCO0d2gZAfZDK3xpSZxZ8o+Y1EYgvsbY5Eu3rgsOPrVHe7EP81bnZ4wI0i9XRHrq1hAPpfgjzMZORVgnAe1XW26os8xnvQqWN9y+tpUPnAm8/cXbFEm1/5gEFC35wnSuhk64G/CkEOp9Uf6jXd+bE2wMkqU705eySnz2RflWPXQM/Ale+Kw/U/6aiAVEFL/dpH+yLYNToq3/+ZUrV2PvX95YsoaB5lKRp1MBAuiSstkV0/2bCJ8TpkvJKRxatmX5CYKv+PbmTDSxuhpkx1CvDXFfhlcD89lf4VEvbw13g5DQa2VnA9LQtGgViX0zgCpHbDjhuXYCmNcFibXT7MFjiMzK1WKc3YtEI3Y4dpAmJ2SEMFfxxDY8mnE082CXZJshKc2EdsPnBLUJsTzYxMsl8oakP8WL3MJoEX7EbBh5geM0uTcweduZfQFDmPX3WA9CNif18x++1Zv8gXcVNUMQTFnuY6eP26u7g7vqftwlqjv2RyBIBm5ibmspm4E/2aXpzXptA6ATfeokjjM2VsJjjq8shL1CCuHf8LMpL+JwuinJ34="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
