travis:
  secure:
    BINSTAR_TOKEN: JcIlMmUPF8IXcMOp9b3qm02xizi4moD1rml7eAz2aJdidL+JTaOlfH4pCvPs9HDC1IT+fvxn30t0pNr9HgkPm5BgysxsevhZciu3QU2fj0EjtahmeNVxc7COQtJeAFCO0d2gZAfZDK3xpSZxZ8o+Y1EYgvsbY5Eu3rgsOPrVHe7EP81bnZ4wI0i9XRHrq1hAPpfgjzMZORVgnAe1XW26os8xnvQqWN9y+tpUPnAm8/cXbFEm1/5gEFC35wnSuhk64G/CkEOp9Uf6jXd+bE2wMkqU705eySnz2RflWPXQM/Ale+Kw/U/6aiAVEFL/dpH+yLYNToq3/+ZUrV2PvX95YsoaB5lKRp1MBAuiSstkV0/2bCJ8TpkvJKRxatmX5CYKv+PbmTDSxuhpkx1CvDXFfhlcD89lf4VEvbw13g5DQa2VnA9LQtGgViX0zgCpHbDjhuXYCmNcFibXT7MFjiMzK1WKc3YtEI3Y4dpAmJ2SEMFfxxDY8mnE082CXZJshKc2EdsPnBLUJsTzYxMsl8oakP8WL3MJoEX7EbBh5geM0uTcweduZfQFDmPX3WA9CNif18x++1Zv8gXcVNUMQTFnuY6eP26u7g7vqftwlqjv2RyBIBm5ibmspm4E/2aXpzXptA6ATfeokjjM2VsJjjq8shL1CCuHf8LMpL+JwuinJ34=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
