travis:
  secure:
    BINSTAR_TOKEN: CQFkYpX9mvkezq/7D3sexWJpxhoHGdaFZbhzAiSBTiud5f6mNxJCk6QpGqx+DvxBwa0/814PYEr76BaRJ7tPIbwQFyKZU3a50U4JQOEl9/lxPe8xvcwaGPVo3jscdoNy2zlYPlYH9gNmybR0fclrYJgYWEPAWeG3b3rWhOm5jB96ilta4B3oaLEY5uG2RENnIeyDpTHFEvxYghbFQHEKgNFcci50iZ6A8tNqVBDtq1M3AT5mcGi1Hgi9KaUxkIl1RdbbA6L6t28o0bja88VcTAaC3gPVI10g4nWD7ak+E62jkOgEA+plPpvGJxkCrWWSRt84k+FHAnOz1rrq7h1vLGLcaAL9i7G/QDNYVfOIY+U4ECMtva7n/QwF0FoU1lyiCXJjq5XQVmqb76csdv7bFNEYabd64cRomBoUheZ3WV21RT4LX9VEax6FeM0ehqO/fAon7m8btZ3r5p0QvPjzYTHqzbNzjeSb3viFzUUJQUCJT97Il+OZ7Qt2VTJ4bTF7vuBkOfZKoaVxiLVYKLeoQGu49q5RVULwgFnI9MfsYwA/jSzDtBTyQop29BPVeKDTfuQF66R9FQLwztjCH0/XZEnzJI73ExEz5A+jwERpuolCUyOASr/YMpBAqowUOMo44kIVSkS073i3EAanFr1AJ7ms7RuML6juswJFc/PysKE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
