appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: R4OwdcEzuPUWyz8/npWllBJLzmLajIXLvx8roHBzusVNrLBcp65A1SfStUyi8tX+GodB9SQWhQRXqqvhXpQg0ESUHSxMwthwsZnH5wbvG0iIwxAeXXva82cGDVrviMk4wPeriBCHToj8fW3E7u9O6nbJbK3t+luGd6C/SVOMXxTclCgmoh0e67DizPo9sbhNb9VlZE6w94OMGfY02DRNUjbURCCIpfdTZCYJVYq61wcAx8zEUm0mR6ZduDRudaZQhEjDDFFyI3YR35PbpsFel1ALYbe6P+aLFAH84YYXmVjsG1aWjbHuFJNRfBz3ceROlKIxcgCa7cCyNh9NEsL4PWGPmxCL7u8RkuV66vL0qiPOyHuLN8l5BxTzOsnyEozFpwm3Fz1FZ7/bEtYOJALtKY2oCyZdqYKFT52iu0E0vAGH2AYJ0TUllwhp58/DEJsz2ILAY66pXauED0NsBLzVjT7s6On8pEuNf8/xh4McugMIayFr+xxxP0J0ICn8zqqmSUmOJrNUSdPaRbltlFOIBYC+iliRGRLcmBmCsPmvw1jW2phiw0Y9olFOgO9PaRReuzkjT5pohFq7D692TEE7b6ZeLVuYY9541nWHMUcLtYSlCBbxZOP+YdqX9cdZoZa5E+3N6gL5Ew2Pd5P5qZ7YgSFz9OuHnoZ9863Yy9hW2UM=}
provider:
  win: azure
conda_forge_output_validation: true
